.bumpversion.cfg, .env.template, README.md, build/synapse/Dockerfile, build/synapse/eth_auth_provider.py, build/synapse/render_config_template.py, build/synapse/synapse-entrypoint.sh, docker-compose.yml, known_servers.main.yaml, known_servers.test.yaml, known_servers.yaml, purge/purge.py
Note: Bumpversion isn't working correctly yet, since it would also increase the version in the changelog. Easiest solution: move changelog to a separate file (we can do this next release)
=> Release 2018.10.0

docker-compose.yml, purge/purge.py
Without it, purger script fails on login and doesn't continue e.g. to nightly restart.
Therefore, also enclosed `purge` function in try/finally block to always run the docker restart (if set) despite exceptions or early return.
=>  Fix port used by purger script to access synapse server

build/synapse/Dockerfile
This way we can use the latest synapse to test against Raiden.
=> Install synapse from source

docker-compose.yml
The services containers have been accidentally removed with #88.
This adds them back.
=> Add back services

build/synapse/Dockerfile
Matrix had a security advisory for a vulnerability issue related ro request-smuggling attacks. nice discovery @palango
Should not be too much of an issue for our use case but they provided an easy fix.
=> fix vulernability in synapse

register-service-provider.sh
The services changed their module name as well as environment variables for registering service in the service registry on chain
=> change to new registration command

docker-compose.yml
accept disclaimer for services
=> accept disclaimer

.env.template, docker-compose.yml
This PR does two things:
- fix ms health check due to typo
- disclaimer must be accepted in .env file in order for the services to run
=> accept disclaimer in .env, fix ms health check

.env.template, docker-compose.yml
- the disclaimer needs to be passed to the request collector as well
=> add accept disclaimer variable to request collector

docker-compose.yml
Added start_period for ms health check
=>  Fix for issue #107

docker-compose.yml
synapse event creator had not been pinned to the env IMAGE_SYNAPSE_VERSION
=> pin event_creator to IMAGE_SYNAPSE_VERSION

docker-compose.yml
This includes https://github.com/raiden-network/raiden-services/issues/758 in the RSB
=> Update services, this includes interactive registration script

known_servers/known_servers.alderaan.yaml
Anyblocks agreed to be the first server in the list for the bootstrapping process
Other proividers will be onboarded shortly afterwards
=> [DO NOT MERGE] Create known_servers_file for release

docker-compose.yml
Part of https://github.com/raiden-network/raiden/issues/6132
=> Update to latest services release

.bumpversion.cfg, CHANGELOG.md, README.md, docker-compose.yml
~~⚠️ Merge only after it's decided if https://github.com/raiden-network/raiden-service-bundle/pull/153 should be merged or not.~~
=> Bump version: 2020.04.0 → 2020.05.0

known_servers/known_servers.alderaan.yaml
=> added raiden.overdoze.se to known alderaan providers

.bumpversion.cfg, CHANGELOG.md, README.md, UPGRADING.md, config/synapse/synapse.template.yaml, docker-compose.yml
Will push the tag once this gets merged to master.
=> Prepare 2020.11.1 release

BUILD_VERSIONS
=> Upgrade Synapse to 1.22.1

README.md
=> Update README.md - better clarification on registering as an RSB provider

build/room_ensurer/room_ensurer.py
Every time when the room ensurer starts (once per hour) it uses a new signer and therefore a new user on the other transport servers to login. This is being replaced by using a constant seed phrase to have a only one signer and therefore one user per RSB.
In this PR I used the admin password which is a random string as the seed phrase as it remains the same for the whole lifetime of an RSB provider.
fixes: #228
=> use password as seed for signer

.env.template, build/rust-synapse-compress-state/Dockerfile, build/rust-synapse-compress-state/compress_state.sh, docker-compose.yml
This adds build information, runner script and  service
for https://github.com/matrix-org/rust-synapse-compress-state
fixes #247
=> Add rust-synapse-compress-state container

CHANGELOG.md, config/synapse/synapse.template.yaml
This was already enabled on test servers.
=> Enable retention policy

BUILD_VERSIONS
=> Update synapse to 1.27.0

docker-compose.yml
Services are now not trying to join broadcast rooms
=> update raiden services to 0.15.1

docker-compose.yml
As described here: https://www.gevent.org/configuration.html#gevent._config.Config.monitor_thread
=> Enable gevent monitoring for services

known_servers/known_servers-development-v3.0.0.json, known_servers/known_servers-production-v3.0.0.json
=> Add federation files for next release
