- README.md
- docker-compose.yml
This changes the compose recipe to use the latest tagged release image for `raidennetwork/raiden-services`.
> Use tagged release image for raiden-services

- .circleci/config.yml
- README.md
- build/synapse/Dockerfile
- docker-compose.yml
This fixes #36 
- The images for `build/*` now reside at https://hub.docker.com/r/raidennetwork/raiden-services-bundle (note the extra `s` in `services` -- follow up: #49)
- The `docker-compose.yml` recipe now uses the `image:` keyword instead of doing a `build:` from local files.
- Building the docker images now happens on [CircleCI](https://circleci.com/gh/raiden-network/raiden-service-bundle)
- The versioning for `docker build` tags the images as: `raidennetwork/raiden-services-bundle:{$TAG}`, where `${TAG}` is of the form `${RELEASE_GIT_TAG}_${SERVICE_NAME}` or `nightly_${SERVICE_NAME}`. (follow-up #50)
Other changes:
- The  [raiden-services](https://github.com/raiden-network/raiden-services) container are now using the `stable` tag.
- Synapse is now at version `v1.4.1`
- `README.md` …
> Add image build automation

- .circleci/config.yml
- BUILD_VERSIONS
- build/db/Dockerfile
- build/well_known_server/Dockerfile
- docker-compose.yml
Fixes #50 
This centralizes the version maintenance for the `raiden-service-bundle` stack.
Version maintenance happens in two places:
1. The file `BUILD_VERSIONS` controls the software versions for the docker images that are built by CircleCI. Upgrading e.g. the `SYNAPSE_VERSION` should happen through a change to this file and a consecutive PR/release.
2. The image versions for running the compose stack are defined inside the `x-versions` section of `docker-compose.yml`. When creating a new release, the image tags inside there should be adjusted to match the expected image tags, e.g. for a `2020.01.0` release:
```diff
x-versions:
services: &IMAGE_RAIDEN_SERVICES_VERSION
image: raidennetwork/raiden-services:stable
db: &IMAGE_DB_VERSION
-    image: …
```
> Tooled versions

- README.md
- docker-compose.yml
- register-service-provider.sh
Fixes #51 
Instead of running the `registration` service automatically on
`docker-compose up..`, there is now a dedicated shell script to register
the service provider: `register-service-provider.sh`.
The `registration` service is removed from `docker-compose.yml`.
The script makes use of the same environment definition (`.env`) as
`docker-compose.yml`, therefore any configuration overhead is avoided.
Yet, it is possible to also run the registration from a different
machine, if necessary.
> Manual registration

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- docker-compose.yml
~After merging, this requires manual tagging through github. I'm unsure, if this is going to trigger a tagged CI build though~
This must be merged through `merge commit` in order to preserve tagging!
> Release 2019.11.0

- .circleci/config.yml
The previous release failed, due to a missing configuration to execute circleCI builds on git tags.
This adds the `workflow` configuration, according to https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag to fix that.
> Execute circleci builds on tags

- docker-compose.yml
The services synchrotron, client_reader, user_dir, event_creator were
removed because the configuration was changed from split to non-split.
> Fixed docker-compose.yml

- docker-compose.yml
As we found out the `purge` container only works on 3.7
> Pin python 3.7 for now

- README.md
The wildcard DNS record also covers the subdomain `pfs.<domain>` A record.
> Removed unnecessary instruction from README

- known_servers.main.yaml
The MyCrypto provided server seems to be offline currently. 
Remove it until it is working again.
> Remove mycrypto server

- known_servers.main.yaml
This reverts commit 071226d5ccec47a585e098383289318bdde99c26.
Reason: It is now online again and they setup alerting so that this is
caught by them earlier if it happens again.
> Reintroduce mycrypto server

- .circleci/config.yml
- .circleci/set_version_tag_or_skip.sh
Refactor the build instructions into a reusable command.
Also no longer clobber the nightly tag for every PR but instead build containers tagged as `PR<number>.<build-number>-<component>`.
Fixes: #78
> Refactor Circle CI config

- docker-compose.yml
With #88 merged we need to use the latest db image until we have a new release.
> Switch to current DB image

- docker-compose.yml
Until now the docker logs would grow without bound, leading to the need for manual intervention after some time.
This limits the log size of the containers to 10 files of max 20MiB each per container.
This means currently with a default configuration of `WORKER_COUNT = 4` the maximum log size will be 20MiB * 10 * 15 = 3GiB
> Limit docker log size

- register-service-provider.sh
According to @karlb the raiden clients only accept a Service URL that uses `https://pfs.${SERVER_NAME}`
@fredo please double-check that it is correct now
> changing registered service url

- docker-compose.yml
Using numbers apparently doesn't work
See the note below: https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver
> Use strings in log config

- build/room_ensurer/room_ensurer.py
first server in the list is now treated as `first-server`
> do not sort servers alphabetically

- docker-compose.yml
This PR adds a prefix to the SERVER_NAME so we can align with the sub domains for pfs and ms.
it will be now:
Matrix: transport.${SERVER_NAME}
PFS: pfs.${SERVER_NAME}
> add prefix transport. as subdomain

- docker-compose.yml
While setting up a new RSB installation some components take longer than others to become operational (due to dependencies on external changes like the federation whitelist for example).
Previously there was a docker healthcheck dependency from MSRC -> MS.
This is problematic since the MS is one of the components that cannot start until the transport server has finalized setting up the bradcast rooms.
Therefore the MSRC wouldn't be started at all making later operator intervention necessary.
Removing this dependency has no negative effect on the setup since the MSRC will automatically restart if it cannot access the MS database.
> Remove MSRC dependency on MS

- register-service-provider.sh
In contrast to docker-compose, the docker cli doesn't support relative
paths when mounting host directories.
> Fix data dir default value in register script

- build/room_ensurer/room_ensurer.py
The case that the list of providers could be extended was not handled for giving admin rights for the broadcast rooms. 
Now the Room Ensurer also ensures that the admin users of the current list are gonna be set in the power levels state event
> ensure admin rights during room ensurer

- docker-compose.yml
The PFS and MSRC got passed the wrong matrix domain (without preceeding `transport.`)
> add correct matrix server domain for msrc and pfs

- known_servers.test.yaml
With the test servers updated to the latest RSB the subdomain scheme has changed.
> Update known servers (test) file

- build/synapse/Dockerfile
- build/synapse/render_config_template.py
The Synapse config renderer script contained a hardcoded and outdated reference to the known federation whitelist.
This is now replaced by reading the value from the current Raiden version during container build.
> Fix outdated known federation url in Synapse config renderer

- known_servers.main.test.yaml
- known_servers.test-split.yaml
The federations for the test setup on goerli and mainnet before the release are down and thus the files can be removed.
> remove unused known servers files

- build/purger/purger.py
- docker-compose.yml
- pyproject.toml
- setup.cfg
The purger script used a hardcoded and outdated list of known federation servers if the container to be checked didn't have the `URL_KNOWN_FEDERATION_SERVERS` env variable set.
This is now fixed to always use the list from the corresponding Raiden version.
Also copies over the pylint, flake8 and isort configs from the main Raiden repo.
> Fix purger known federation servers

- README.md
This additionally includes a small grammatically mistake. That was part
of the referenced header used as anchor for the hash route.
> Fix broken referenced section link in README

- build/purger/purger.py
- tests/test_purger.py
- tests/utils.py
New Admin API endpoints improve user purging
The user purger was refactored to use new endpoints and additionally clean up the database besides reducing operational load.
A new admin api endpoint allows a server admin to fetch the current members of a room. This is much more convinient and efficients then querying all state events of the room.
Inactive users now gets deactivated and erased from the database. This has a couple of advantages. Besides freeing up space for the user data, footprints of the users also gets erased. They get removed from all rooms they have joined, including private rooms. Furthermore, empty rooms automatically get removed as well.
These optimizations should help the database to be cleaned up where it is possible.
> Admin api improvements [DO NOT MERGE BEFORE SYNAPSE UPGRADE]

- config/traefik/traefik.toml
- docker-compose.yml
- Expose PFS & MS metrics
- They are available from the whitelisted IPs on:
- `metrics.pfs.<server-name>/metrics`
- `metrics.ms.<server-name>/metrics`
- Fix http -> https redirect
Fixes: #160
> Expose PFS, MS metrics & Fix HTTPS redirect

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- UPGRADING.md
- docker-compose.yml
Upgrade to Raiden Services `v0.13.1` to fix a mishap with the metrics path.
> Release 2020.10.1

- build/room_ensurer/room_ensurer.py
When a server isn't reachable a KeyError was occuring in `._get_room()`
> Fix a KeyError in the room_ensurer

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- docker-compose.yml
Fix an issue in the release process.
The bumpversion config file didn't include the `docker-compose.yaml` which lead to old container builds being used.
> Release 2020.10.3

- build/synapse/Dockerfile
The `Dockerfile` accidentally created a file, where it was the 
intention to select a certain version with `pip install`.
> Avoid file redirection when choosing pip version

- config/synapse/synapse.template.yaml
In our test federation all servers have
showed steep increase in db size with each retention policy related
purging run.
Until we have clear signs of improvement for that behavior, we should
disable it per default.
> [synapse] Disable retention policy

- docker-compose.yml
~~Unfortunately pulling a tag other than `latest` from quay.io results in~~
```
ERROR: manifest for quay.io/prometheus/node-exporter:v2.22.1 not found: manifest unknown: manifest unknown
```
~~so I'm tagging it `latest` for now.~~
Changed to the correct tag for the image `prometheus/node_exporter` which is `v1.0.1`. This works now reliably. Sorry, my bad!
> [node_exporter] Change image tag

- register-service-provider.sh
The service registration script used to source `.env`.
This was problematic because the docker .env files have different quoting rules (namely quotes are preserved) than bash.
That would lead to syntax errors if any value in `.env` contained spaces.
> Fix service registration script quoting issues

- README.md
The old address must have been on of the test deployments.
> Update registry contract address

- config/synapse/synapse.template.yaml
Running the `room_ensurer` against a server that has too low `rc_joins` settings can lead to an inconsistent server
state, where rooms are created but can not be joined by the admin account in order to set up the correct power levels.
These values were found "empirically", by restarting the test federation from scratch until it finally worked.
One extra note: The working setup was acquired by bringing up the federation _without_ the `room_ensurer`, and then
manually adding the `room_ensurer` one by one:
```bash
for SERVER in $SERVER_LIST; 
do 
ssh $SERVER "cd /etc/containers/rsb && docker-compose down && \
rm -r /data/200gb/rsb-db" &; 
done
for SERVER in $SERVER_LIST; 
do 
ssh $SERVER "mkdir /data/200gb/rsb-db && cd /etc/containers/rsb && \
docker-compose up --scale room_ensurer=0 -d" &; …
```
> Increase rate limits to fix initial room ensurer

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- UPGRADING.md
- docker-compose.yml
This new release fixes a mistake from `2020.11.1`. 
Also the newest `raiden-services` are included.
I will push the tag, once this gets merged.
> Release 2020.11.2

- README.md
- register-service-provider.sh
The `register-service-provider.sh` script used to be hard-coded to the `register` subcommand.
This now allows all commands to be used.
> Allow to pass subcommands to service registry script

- build/synapse/eth_auth_provider.py
The `ETHAuthProvider` does not need to register the device id to `raiden` as we log into the servers with `device_id` explicitly set. It will register automatically.
> Remove device id regstration in auth provider

- build/room_ensurer/room_ensurer.py
Fixes a wrongly un-negated boolean statement.
This was not critical since the variable only affects logging.
> Fix boolean statement negation

- known_servers/known_servers-production-v1.2.0.json
The Matrix server seems to be running.
``` fish
[I] ➜ http https://transport.raijin1.raiden.ninja/_matrix/client/versions
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 353
Content-Type: application/json
Date: Mon, 18 Jan 2021 15:34:08 GMT
Server: Synapse/1.22.1
{
"unstable_features": {
"io.element.e2ee_forced.private": false,
"io.element.e2ee_forced.public": false,
"io.element.e2ee_forced.trusted_private": false,
"org.matrix.e2e_cross_signing": true,
"org.matrix.label_based_filtering": true,
"org.matrix.msc2432": true,
"uk.half-shot.msc2666": true
},
"versions": [ …
```
> Add raijin1.raiden.ninja to federation whitelist

- build/purger/purger.py
Fetching members request used the wrong `api_path` resulting in not being able to fetch and therefor purge members. This is fixed now, and tested on transport01
fixes: #242
> fix request to fetch members from public rooms

- build/room_ensurer/room_ensurer.py
With the change to to_device messaging with services, the only global room used is the discovery room. Therefore this is the only room to be ensured.
fixes: #255
> Only ensure discovery room

- docker-compose.yml
The way that passwords from environment variables are handled, changed in an incompatible way.
By moving the password into the command options, we can work around that.
> Change password handling for raiden-services

- docker-compose.yml
The Purger is temporarily disabled as it need to fetch presence from the PFS. This will come with the update
> disable purger temporarily

- .circleci/config.yml
#277 removed the compress_state service.
This also removes the now stale CI build instructions for it.
> Remove CI build rule for compress_state image

- config/synapse/synapse.template.yaml
For unknown reasons the Synapse module by Raiden for the presence started to throw issues on parsing the configuration file. The `service_registry_address` option in the module configuration gets parsed as an integer. In the following the `eth_utils` functions fail to parse this number as a valid Ethereum address. In result the whole server fails to start.
The exact origin of this new problem is not known. Maybe the parsing of hex values in a YAML file get now specially parsed and not taken are pure strings anymore. In any case a simple solution is to explicitly make the value a string by putting quotation marks around it in the configuration template file. This change is not invasive and is also backwards compatible.
> fix Synapse configuration file format

- .bumpversion.cfg
- .circleci/config.yml
- CHANGELOG.md
- README.md
- build/synapse/Dockerfile
- docker-compose.yml
- known_servers/known-servers_arbitrum-one_2022-05-0.json
Successor of #299. Please see [this comment](https://github.com/raiden-network/raiden-service-bundle/pull/299#issuecomment-1114888223) for more details.
This PR stays in draft mode in preparation of the release until the new CI built images got tested with a practical RSB setup.
> Chore/release 2022-05-0
